version: 2.1

executors:
  google-executor:
    docker:
      - image: gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine
    working_directory: ~/repo

jobs:
  build:
    executor: google-executor
    steps:
      - checkout  # Faz o checkout do código do repositório

      - run:
          name: Debug Environment Variables
          command: env | grep azul || echo "azul não está definida!"

      - run:
          name: Authenticate Google Cloud
          command: |
            # Verificando o conteúdo da variável MY_GOOGLE_CREDENTIALS
            echo "Conteúdo da variável MY_GOOGLE_CREDENTIALS:"
            # echo "$MY_GOOGLE_CREDENTIALS"  # Isso deve exibir a chave JSON
            echo "$azul"  # Isso deve exibir a chave JSON

          ## Garantir que a variável não está vazia
          #if [ -z "$MY_GOOGLE_CREDENTIALS" ]; then
          #  echo "A variável MY_GOOGLE_CREDENTIALS está vazia!"
          #  exit 1
          #fi

          ## Criar o arquivo de chave JSON temporário
          #echo "$MY_GOOGLE_CREDENTIALS" | base64 -d > /tmp/gcp-credentials.json

          ## Verificar se o arquivo foi criado corretamente
          #cat /tmp/gcp-credentials.json

          ## Ativar a conta de serviço usando a chave temporária
          #gcloud auth activate-service-account --key-file=/tmp/gcp-credentials.json
          #gcloud config set project original-nation-453118-a7  # Defina o seu ID do projeto

      - run:
          name: Create Bucket on GCS
          command: |
            BUCKET_NAME=my-bucket
            gsutil mb gs://$BUCKET_NAME/  # Cria o bucket no GCS

      - run:
          name: Upload files to GCS
          command: |
            gsutil cp path/to/your/file gs://$BUCKET_NAME/

workflows:
  version: 2
  deploy:
    jobs:
      - build

context: gordon








